import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* Let Next.js manage <html> tag statically */}
      <html lang="en" suppressHydrationWarning>
        {/* ThemeProvider needs to be inside <body> */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen">
              <Navbar />
              <main className="py-8">
                <div className="max-w-7xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    <div className="hidden lg:block lg:col-span-3">
                      <div className="space-y-4 p-4 border-r h-full text-sm text-muted-foreground">
                        <div className="text-base font-semibold text-foreground">Navigation</div>
                        <div className="flex flex-col space-y-2">
                          <Link href="/labmembers" className="hover:underline text-primary">
                            Lab Members
                          </Link>
                          <Link href="/publications" className="hover:underline text-primary">
                            Publications
                          </Link>
                          <Link href="/research" className="hover:underline text-primary">
                            Research
                          </Link>
                        </div>
                      </div>
                    </div>
                    <div className="lg:col-span-9">{children}</div>
                  </div>
                </div>
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
